import { and, desc, eq, gte, lt } from "drizzle-orm";
import { db, schema, logger } from "@onrecord/core";

// ---------------------------------------------------------------------------
// Daily digest (spec §1.6): top 3–5 stories by rank plus counts. Generated by
// cron; the natural future subscription/agent product.
// ---------------------------------------------------------------------------

export async function generateDigest(date: string): Promise<void> {
  const dayStart = new Date(`${date}T00:00:00Z`);
  const dayEnd = new Date(dayStart.getTime() + 86_400_000);

  const dayStories = await db
    .select()
    .from(schema.stories)
    .where(
      and(
        gte(schema.stories.createdAt, dayStart),
        lt(schema.stories.createdAt, dayEnd),
        eq(schema.stories.status, "published"),
      ),
    )
    .orderBy(desc(schema.stories.rankScore));

  const dayEvents = await db
    .select({ type: schema.events.type, enrichment: schema.events.enrichment })
    .from(schema.events)
    .where(
      and(
        gte(schema.events.createdAt, dayStart),
        lt(schema.events.createdAt, dayEnd),
        eq(schema.events.network, "mainnet"),
      ),
    );

  const deploys = dayEvents.filter((e) => e.type === "deploy");
  const copies = deploys.filter((e) => {
    const cls = (e.enrichment as { classification?: { disposition?: string } }).classification;
    return cls?.disposition === "copy" || cls?.disposition === "near_copy";
  });

  const counts = {
    storiesToday: dayStories.length,
    launchesToday: dayStories.filter((s) => s.type === "launch").length,
    updatesToday: dayStories.filter((s) => s.type === "update").length,
    deploysSeen: deploys.length,
    copyPercent: deploys.length ? Math.round((copies.length / deploys.length) * 100) : 0,
  };

  await db
    .insert(schema.digests)
    .values({ date, storyIds: dayStories.slice(0, 5).map((s) => s.id), counts })
    .onConflictDoUpdate({
      target: schema.digests.date,
      set: { storyIds: dayStories.slice(0, 5).map((s) => s.id), counts },
    });

  logger.info({ date, ...counts }, "digest generated");
}
